---
# StoragePlan: database_plan
apiVersion: privatecloud.mendix.com/v1alpha1
kind: StoragePlan
metadata:
  creationTimestamp: null
  labels:
    privatecloud.mendix.com/storage-class: ""
    privatecloud.mendix.com/storage-plan: ep-db
    privatecloud.mendix.com/storage-type: database
  name: ep-db
spec:
  create:
    args:
    - --from-value={"DatabaseType":"HSQLDB","DatabaseName":"db"}
    command:
    - create
    instanceNameTemplate: mendix-{{.Name}}-{{.UUID}}
    resources:
      limits:
        cpu: 500m
        memory: 64Mi
      requests:
        cpu: 100m
        memory: 64Mi
    serviceAccountName: mendix-storage-provisioner
  delete:
    command:
    - delete
    resources:
      limits:
        cpu: 500m
        memory: 64Mi
      requests:
        cpu: 100m
        memory: 64Mi
  provisioner: basic
  type: on-demand
status: {}
...
---
# StoragePlan: storage_plan
apiVersion: privatecloud.mendix.com/v1alpha1
kind: StoragePlan
metadata:
  creationTimestamp: null
  labels:
    privatecloud.mendix.com/storage-class: ""
    privatecloud.mendix.com/storage-plan: ep-st
    privatecloud.mendix.com/storage-type: file
  name: ep-st
spec:
  create:
    args:
    - --from-value={}
    command:
    - create
    instanceNameTemplate: mendix-{{.Name}}-{{.UUID}}
    resources:
      limits:
        cpu: 500m
        memory: 64Mi
      requests:
        cpu: 100m
        memory: 64Mi
    serviceAccountName: mendix-storage-provisioner
  delete:
    command:
    - delete
    resources:
      limits:
        cpu: 500m
        memory: 64Mi
      requests:
        cpu: 100m
        memory: 64Mi
  provisioner: basic
  type: on-demand
status: {}
...
