# Rendered Chart mx-privatecloud-operator-versions-2.5.1
---
# Source: mx-privatecloud-operator-versions/templates/mx-operator-versions.yaml
apiVersion: privatecloud.mendix.com/v1alpha1
kind: OperatorVersion
metadata:
  name: mendix-operator-version
spec:
  versions:
    repository_url: "private-cloud.registry.mendix.com"
    builder_version: "2.3.1"
    metrics_sidecar_version: "2.2.1"
    operator_version: "2.5.1"
    sidecar_version: "2.2.1"
    storage_provisioner_version: "2.3.2"

# Rendered Chart mx-privatecloud-operator-2.5.1
---
# Source: mx-privatecloud-operator/templates/mx-operator-service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mendix-operator
---
# Source: mx-privatecloud-operator/templates/mx-operator-storage-provisioner-sa.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mendix-storage-provisioner
---
# Source: mx-privatecloud-operator/templates/mx-operator-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mendix-operator
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - endpoints
      - persistentvolumeclaims
      - events
      - configmaps
      - secrets
    verbs:
      - '*'
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - '*'
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors
    verbs:
      - get
      - create
  - apiGroups:
      - "extensions"
      - "networking.k8s.io"
    resources:
      - ingresses
    verbs:
      - get
      - create
      - list
      - watch
      - update
  - apiGroups:
      - route.openshift.io
    resources:
      - routes
    verbs:
      - get
      - create
      - list
      - watch
      - update
  - apiGroups:
      - route.openshift.io
    resources:
      - routes/custom-host
    verbs:
      - create
      - update
  - apiGroups:
      - apps
    resourceNames:
      - mendix-operator
    resources:
      - deployments/finalizers
    verbs:
      - update
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
  - apiGroups:
      - apps
    resources:
      - replicasets
    verbs:
      - get
  - apiGroups:
      - privatecloud.mendix.com
    resources:
      - '*'
      - builds
      - runtimes
      - mendixapps
      - operatorconfigurations
      - endpoints
      - storageplans
      - storageinstances
      - operatorversions
    verbs:
      - '*'
---
# Source: mx-privatecloud-operator/templates/mx-operator-storage-provisioner-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mendix-storage-provisioner
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - 'create'
---
# Source: mx-privatecloud-operator/templates/mx-operator-role-binding.yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mendix-operator
subjects:
  - kind: ServiceAccount
    name: mendix-operator
roleRef:
  kind: Role
  name: mendix-operator
  apiGroup: rbac.authorization.k8s.io
---
# Source: mx-privatecloud-operator/templates/mx-operator-storage-provisioner-role-binding.yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mendix-storage-provisioner
subjects:
  - kind: ServiceAccount
    name: mendix-storage-provisioner
roleRef:
  kind: Role
  name: mendix-storage-provisioner
  apiGroup: rbac.authorization.k8s.io
---
# Source: mx-privatecloud-operator/templates/mx-operator-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mendix-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mendix-operator
  template:
    metadata:
      labels:
        name: mendix-operator
    spec:
      serviceAccountName: mendix-operator
      containers:
        - name: mendix-operator
          image: "private-cloud.registry.mendix.com/mendix-operator:2.5.1"
          command:
            - mendix-operator
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "mendix-operator"
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
# Source: mx-privatecloud-operator/templates/mx-operator-configuration.yaml
apiVersion: privatecloud.mendix.com/v1alpha1
kind: OperatorConfiguration
metadata:
  name: mendix-operator-configuration
spec:
  buildRuntimeBaseImage: "private-cloud.registry.mendix.com/runtime-base:{{.MxRuntimeVersion}}-rhel"
  buildResources:
    limits:
      cpu: "1"
      memory: 256Mi
    requests:
      cpu: 250m
      memory: 64Mi
  sidecarResources:
    limits:
      cpu: 250m
      memory: 32Mi
    requests:
      cpu: 100m
      memory: 16Mi
  metricsSidecarResources:
    limits:
      cpu: 100m
      memory: 32Mi
    requests:
      cpu: 100m
      memory: 16Mi
  runtimeResources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 512Mi
  runtimeMetricsConfiguration:
    interval: PT1M
    mode: native
  endpoint:
    type: ingress

